## PlayBook提供更强大更灵活的批量多任务 执行 ansible-playbook  ansible-playbook.yaml

- hosts: testgroup
  tasks:
    - name: test ansible
      shell: echo "shell 1" >>/tmp/a
    - name: test copy
      copy: src=/tmp/a dest=/usr/local/src/
      #when: inventory_hostname == "host1IP"

- name: Upload files to hosts with the same IP
  hosts: testgroup2
  gather_facts: no
  tasks:
    - name: Upload files
      ansible.builtin.copy:
        src: /root/tmp.txt  # 本地文件路径
        dest: /home/panweiji
      delegate_to: "{{ item.host }}"
      vars:
        ansible_port: "{{ item.port }}"
      with_items:
        - { host: 'IP地址', port: '端口号1' }
        - { host: 'IP地址', port: '端口号2' }