# 在集群中创建Secret 参考文档: https://help.aliyun.com/document_detail/409430.html
apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
data:
  access-key: YOUR_ACCESS_KEY_BASE64  #base64编码后的AccessKey ID。执行 echo -n <AccessKey ID> | base64
  secret-key: YOUR_SECRET_KEY_BASE64  #base64编码后的AccessKey Secret。