# 创建一个集群级的签发机构 仅需一次
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  # ACME 协议的服务端  acme-staging-v02测试证书没有限制
    email: 406798106@qq.com  # 证书快过期的时候会有邮件提醒
    privateKeySecretRef:
      name: letsencrypt-prod-key  # 私钥秘密必须与cert-manager服务在同一个命名空间中才能工作 kubectl delete Secret letsencrypt-prod-key --namespace cert-manager
    solvers:
      - http01: # 签发机构使用 HTTP-01 的方式进行 acme 协议 (还可用 DNS 方式，acme 协议的目的是证明机器和域名都是属于你的，然后才准许颁发证书)
          ingress:
            #serviceType: ClusterIP
            name: pengbocloud-k8s-ingress  # 这个匹配是关键！！！  1. class是指定自动创建的 Ingress 的 ingress class  2. name是指定被自动修改的 Ingress 名称

#---
#
## 创建一个证书
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: cert-manager-tls
#  namespace: cert-manager
#spec:
#  secretName: saas.pengbocloud.com-tls  # 最终签发出来的证书会保存在这个 Secret 里面
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-prod # 引用 Issuer
#  dnsNames:
#    - saas.pengbocloud.com # 要签发证书的域名

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pengbocloud-k8s-ingress
  namespace: default
  annotations:
    # 指定使用nginx做代理
    #kubernetes.io/ingress.class: lanneng-k8s-ingress  # 已弃用 使用 spec.ingressClassName代替
    # add an annotation indicating the issuer to use
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    #cert-manager.io/issue-temporary-certificate: "true"
    #kubernetes.io/tls-acme: "true"
    #ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/enable-cors: "true"
    #nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #acme.cert-manager.io/http01-override-ingress-class: lanneng-k8s-ingress

spec:
  ingressClassName: lanneng-k8s-ingress
  tls:
    - hosts:
        #自定义域名
        - saas.pengbocloud.com
      secretName: saas.pengbocloud.com-tls
  rules:
    #自定义域名
    - host: saas.pengbocloud.com
      http:
        paths:
          - path: /
            backend:
              #服务名称
              service:
                name: openpark-saas-admin-web-service
                #服务端口
                port:
                  number: 8025
            pathType: Prefix