apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
  namespace: istio-system
spec:
  # The secretName will store certificate content
  secretName: istio-ingressgateway-certs
  commonName: istio-ingressgateway-certs
  dnsNames:
    # Replace to your real DNS name
    - example.com
    - "*.example.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer