# 在集群中创建Secret 参考文档: https://help.aliyun.com/document_detail/409430.html
apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
data:
  access-key: YOUR_ACCESS_KEY_BASE64  #base64编码后的AccessKey ID。执行 echo -n <AccessKey ID> | base64
  secret-key: YOUR_SECRET_KEY_BASE64  #base64编码后的AccessKey Secret。


---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
  namespace: istio-system
spec:
  # The secretName will store certificate content
  secretName: istio-ingressgateway-certs
  commonName: istio-ingressgateway-certs
  dnsNames:
    # Replace to your real DNS name
    - example.com
    - "*.example.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer


---

# 在集群中创建ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.yourcompany.com
            solverName: alidns
            config:
              region: ""
              accessKeySecretRef:
                name: alidns-secret
                key: access-key
              secretKeySecretRef:
                name: alidns-secret
                key: secret-key