bindPort = 7000
auth.token = "YRgC=Vh*WD6v:xp-Ab-Ng3@=0F*+.fD7*r,)8i.La^yi,d!79vNZHLbaR50r"

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "Admin@0633"