bindPort = 7000   # frp服务端口
vhostHTTPPort = 8008 # http服务端口
auth.token = ".=:N!uLm!RtrY_MxvNZGzM3^LH2-h#co!k3wbH.i~BXCMa-JAh?>Q=GWp2JQ"

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "Admin@0633"


# 日志配置文件
#log_file = "./frps.log"           # 日志文件,不指定日志信息默认输出到控制台
#log_level = "info"                # 日志等级，可用等级“trace, debug, info, warn, error”
#log_max_days = 3                # 日志保存最大保存时间

# 允许客户端设置的最大连接池大小，如果客户端配置的值大于此值，会被强制修改为最大值，默认为 5
#maxPoolCount