bindPort = 7000
#vhostHTTPPort = 8080 # http服务监听端口
auth.token = ".=:N!uLm!RtrY_MxvNZGzM3^LH2-h#co!k3wbH.i~BXCMa-JAh?>Q=GWp2JQ"

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "Admin@0633"