# 全局配置
global:
  scrape_interval:     15s   # 多久 收集 一次数据
  evaluation_interval: 15s   # 多久评估一次 规则
  scrape_timeout:      10s   # 每次 收集数据的 超时时间

# 告警alertmanager配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:  ['172.31.88.89:9093']

# 规则文件, 可以使用通配符
rule_files:
  - "rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.16.100.185:9100']

  - job_name: 'mysql_node_exporter'
    static_configs:
      - targets: ['172.16.100.185:9104']


#  # Spring Boot应用配置
#  - job_name: 'property-sales-app'
#    scrape_interval: 5s
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['172.31.88.89:8096']
#
#  # Spring Boot应用配置
#  - job_name: 'property-sales-mapp'
#    scrape_interval: 15s
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['172.31.88.89:8095']