# Author: 潘维吉
# Description: 云原生K8S应用根据QPS自定义指标弹性扩缩容

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {APP_NAME}-hpa
  namespace: default

spec:
  minReplicas: {K8S_POD_REPLICAS}    # 缩容最小节点数
  maxReplicas: 10                    # 扩容最大节点数
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {APP_NAME}-deployment
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_server_requests_qps  # 基于QPS自动伸缩 安装 prometheus-adapter 来实现基于自定义指标的 Pod 弹性伸缩
        target:
          type: AverageValue
          averageValue: 300  # 当每个业务Pod的QPS指标平均值高于时，触发自动进行扩容

#    - type: Resource
#      resource:
#        name: "cpu"
#        targetAverageUtilization: 50 # CPU超过多少  触发自动进行扩容
#    - type: Resource
#      resource:
#        name: "memory"
#        targetAverageValue: 4000Mi # 当内存超过多少时，触发自动进行扩容

---

#  kubectl get hpa