apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gray-release-canary
  namespace: default
  annotations:
    # 开启Canary。
    nginx.ingress.kubernetes.io/canary: "true"
    # Http Header请求头为version。
    nginx.ingress.kubernetes.io/canary-by-header: "version"
    # 请求头version=v2.0.0时，请求才会被路由到新版本服务中。
    nginx.ingress.kubernetes.io/canary-by-header-value: "v2.0.0"
    # 在满足上述匹配规则的基础上仅允许百分比的流量会被路由到新版本服务中。
    nginx.ingress.kubernetes.io/canary-weight: "100"
    # 开启跨域
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # 数据传输大小
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    # 数据请求超时时间
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # 负载均衡算法 如ip_hash
    nginx.ingress.kubernetes.io/upstream-hash-by: "$host"


spec:
  rules:
    - host: new-version.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: {APP_NAME}-service
                port:
                  number: {HOST_PORT}
            pathType: ImplementationSpecific
#    - host: old-version.com
#      http:
#        paths:
#          - path: /
#            backend:
#              service:
#                name: oldServiceName
#                port:
#                  number: 80
#            pathType: ImplementationSpecific


# 删除Ingress
# kubectl delete ingress ingress-name