apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APP_NAME}-deployment
  namespace: default
  labels:
    app: {APP_NAME}
spec:
  replicas: 3
  #minReplicas: 2                    #最小副本数
  #maxReplicas: 6                    #最大副本数
  selector:
    matchLabels:
      app: {APP_NAME}
  template:
    metadata:
      labels:
        app: {APP_NAME}
    spec:
      containers:
      - name: {APP_NAME}
        image: {IMAGE_URL}:{IMAGE_TAG}
        ports:
        - containerPort: {CONTAINER_PORT}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: {SPRING_PROFILE}
      # 私有镜像配置
      #imagePullSecrets:
        #- name: myregistrykey

---

apiVersion: v1
kind: Service

metadata:
  name: {APP_NAME}-service
  namespace: default
  labels:
    app: {APP_NAME}-service

spec:
  type: NodePort                       # 规格类型，选择LoadBalancer是因为我们要实现Pod之间的负载均衡
  selector:
    app: {APP_NAME}                    # 通过Pod的labels指定Pod 建立关联
  ports:
    - name: {APP_NAME}
      port: {HOST_PORT}                # 指定Service接收请求的端口
      targetPort: {HOST_PORT}          # 请求转发的端口
      nodePort: {HOST_PORT}
      protocol: TCP                    # 定义通信协议
