# Author: 潘维吉
# Description: 若已安装 prometheus-operator，则可通过创建 ServiceMonitor 的 CRD 对象配置 Prometheus

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {APP_NAME}-service-monitor
spec:
  endpoints:
    - port: http
      interval: 5s
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: {APP_NAME}-hpa