rules:
- seriesQuery: '{__name__=~"^http_server_requests_seconds_.*",container!="POD",namespace!="",pod!=""}'  # 指标名称确认存在
  resources:
    overrides:
      namespace:
        resource: namespace
      pod_name:
        resource: pod
  name:
    matches: "^http_server_requests_seconds_count(.*)"
    as: "http_server_requests_seconds_count_sum" # PromQL 计算出来的 QPS 指标
  #metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,uri=~"/.*"}) by (<<.GroupBy>>)
  metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
prometheus:
  url: http://120.92.49.181 # 替换安装的 Prometheus服务地址 (不写端口) 并设置好 prometheus.yml文件要关联监听的服务 保证服务targets正常运行
  port: 9090
  path: ""