# Author: 潘维吉
# Description: 实现基于QPS自定义Prometheus指标的 Pod 弹性伸缩
rules:
  default: false
  custom:
    - seriesQuery: 'http_server_requests_seconds_count'  # 指标名称确认存在  Spring Boot2的http_server_requests_seconds_count是http请求总数 只要Prometheus服务端不重启就一直累加
      resources:
        template: <<.Resource>>
      name:
        matches: "http_server_requests_seconds_count"
        as: "http_server_requests_qps" # PromQL 计算出来的 QPS 指标  以每多少分钟为时间段计算为qps
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)

prometheus:
  url: http://120.92.140.217 # 替换安装的 Prometheus服务地址 (不写端口) 并设置好 prometheus.yml文件要关联监听的服务 保证服务targets正常运行
  port: 9090
  path: ""