# Author: 潘维吉
# Version 1.0.0
# Description: 自定义构建Jenkins Inbound Agent镜像使用K8S构建部署

FROM docker.lanneng.tech/jenkins/inbound-agent:latest

USER root

# 安装常用工具
RUN apt-get update && \
    apt-get install -y \
    procps \
    curl \
    git \
    vim \
    unzip \
    iputils-ping \
    net-tools \
    docker.io

USER jenkins


# 镜像构建 并上传到镜像仓库
# docker build -t docker.lanneng.tech/panweiji/jenkins-agent:latest -f /my/Dockerfile.jenkins-inbound-agent . --no-cache
# docker push docker.lanneng.tech/panweiji/jenkins-agent:latest